### ISSUE TITLE
Problem with connecting to the new VCSA

### ISSUE THREAD

**Issue by eyosam147** [lamw/vsphere-8-lab-deployment#2]
Many thanks for this script,
I'm trying to deploy these servers on my differents labs but the script block after the deploiement of the new VCSA, even if i'll add a big sleep between the "Disconnect-VIServer" and "Connecting to the new VCSA". If I try to connect manually with WebUI on the new vCenter v8 it works....
My lab environnement is based on "fast" hardware (Xeon gen8th and little SAN for storage).
![image](https://user-images.githubusercontent.com/116069845/196389310-f68d61d0-a2ee-412e-9f8e-764db7438840.png)

![image](https://user-images.githubusercontent.com/116069845/196390568-b62169b8-346a-40ef-b332-4a8d5fcb60e8.png)

**Comment by lamw** [comment]
The reason is that your PowerCLI profile (by default) does not trust self-signed certificate, so it fails the connection. You need to update your PowerCLI setting using https://developer.vmware.com/docs/powercli/latest/vmware.vimautomation.core/commands/set-powercliconfiguration/#Default and use `-InvalidCertificateAction` and set it to Ignore
